### ISSUE TITLE
cloud9.ide.filelist error

### ISSUE THREAD

**Issue by smallertomato** [ajaxorg/ace#2292]
IDE server initialized. Listening on 0.0.0.0:3131
Exception found:
Process terminated with code 1, find: 无效断言“-O3”

Process terminated with code 1, find: 无效断言“-O3”

    at Object.handle (/home/chaoliu/websites/cloud9/plugins-server/cloud9.core/middleware.js:18:19)
    at next (/home/chaoliu/websites/cloud9/node_modules/connect/lib/http.js:199:17)
    at /home/chaoliu/websites/cloud9/node_modules/connect/lib/middleware/router.js:177:23
    at /home/chaoliu/websites/cloud9/plugins-server/cloud9.ide.filelist/filelist-plugin.js:86:36
    at ChildProcess.<anonymous> (/home/chaoliu/websites/cloud9/plugins-server/cloud9.ide.filelist/filelist.js:65:17)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:820:12)

**Comment by nightwing** [comment]
Looks like your version of find doesn't support -O3 argument used at
https://github.com/ajaxorg/cloud9/blob/master/plugins-server/cloud9.ide.filelist/filelist.js#L91
try updating find or changing the command.
Closing since this is not related to Ace

**Comment by smallertomato** [comment]
You are right. I read the man page for find  at http://man7.org/linux/man-pages/man1/find.1.html.
In version 4.2.27 ,  find has no option -Olevel . Thank you
