### ISSUE TITLE
Minification fails on Windows

### ISSUE THREAD

**Issue by timdp** [ajaxorg/ace#2351]
Clean clone of master branch, Windows 8.1 Pro:

```shell
C:\tmp\ace>node ./Makefile.dryice.js -m
Processing 65 files.
Compressing:  false
- Failed to compile code: Unterminated string constant (line: 15206, col: 17, pos: 500826)

Error
    at new JS_Parse_Error (C:\tmp\ace\node_modules\dryice\node_modules\uglify-js\lib\parse-js.js:263:18)
    at js_error (C:\tmp\ace\node_modules\dryice\node_modules\uglify-js\lib\parse-js.js:271:11)
    at parse_error (C:\tmp\ace\node_modules\dryice\node_modules\uglify-js\lib\parse-js.js:367:9)
    at with_eof_error (C:\tmp\ace\node_modules\dryice\node_modules\uglify-js\lib\parse-js.js:595:32)
    at read_string (C:\tmp\ace\node_modules\dryice\node_modules\uglify-js\lib\parse-js.js:433:16)
    at Object.next_token [as input] (C:\tmp\ace\node_modules\dryice\node_modules\uglify-js\lib\parse-js.js:608:44)
    at next (C:\tmp\ace\node_modules\dryice\node_modules\uglify-js\lib\parse-js.js:719:25)
    at vardefs (C:\tmp\ace\node_modules\dryice\node_modules\uglify-js\lib\parse-js.js:1064:17)
    at var_ (C:\tmp\ace\node_modules\dryice\node_modules\uglify-js\lib\parse-js.js:1077:26)
    at prog1 (C:\tmp\ace\node_modules\dryice\node_modules\uglify-js\lib\parse-js.js:1312:15)
Written output in 'C:\tmp\ace\build\src-min/mode-abap.js'
Written output in 'C:\tmp\ace\build\src-min/ace.js'
[snip]
```

I tried the exact same sequence of commands on a Linux box and it worked fine. Versions:

- Windows (failing): Node 0.10.36, npm 2.4.1
- Linux (working): Node 0.10.25, npm 1.3.10

Anything I can do to help?

**Comment by nightwing** [comment]
I cannot reproduce this. Does it work without `-m` and if it does what text do you see on line 15206 in non minified file?
This might be caused by broken handling of windows style line endings.

**Comment by timdp** [comment]
Without `-m`, it does work. I don't know if the generated code is valid though; doesn't it just _seem_ to work because UglifyJS is also "responsible" for the syntax check?

The minification happens in memory, so there is no non-minified file. However, I temporarily added an `fs.writeFileSync` to `Makefile.dryice.js` and checked the result. It looks like `virtual_renderer.js`'s import of `editor.css` is the culprit. The injected CSS string apparently contains a newline.

The newline occurs [right where there's a CSS comment](https://github.com/ajaxorg/ace/blob/master/lib/ace/css/editor.css#L361) in the source file. Looks like something in the build chain has trouble with that comment then. If I remove it, the error disappears.

**Comment by nightwing** [comment]
https://github.com/ajaxorg/ace/pull/2355 should fix the issue. Thank you for helping

**Comment by timdp** [comment]
I'd just figured it out myself, but my fix uses `JSON.stringify` rather than regexp magic.
