### ISSUE TITLE
contextify (dependency of node-jsdom) causes build error during npm install

### ISSUE THREAD

**Issue by westonized** [ajaxorg/ace#2789]
I get this problem and there are a few complicated work arounds, but I can build ace just fine without node-jsdom. Is it still needed or can it be removed from `package.json`?

````
2015-12-02T09:08:56.2296964Z C:\Program Files\nodejs\npm.cmd  install
2015-12-02T09:08:58.9015953Z ##[error]npm WARN package.json ace@1.2.2 No license field.
2015-12-02T09:09:12.6360993Z > contextify@0.1.15 install D:\tfs-agent1\_work\f810d0d0\AceEditor\node_modules\node-jsdom\node_modules\contextify
2015-12-02T09:09:12.6360993Z > node-gyp rebuild
2015-12-02T09:09:12.6517286Z D:\tfs-agent1\_work\f810d0d0\AceEditor\node_modules\node-jsdom\node_modules\contextify>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 
2015-12-02T09:09:20.0111501Z Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
2015-12-02T09:09:22.4955630Z TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [D:\tfs-agent1\_work\f810d0d0\AceEditor\node_modules\node-jsdom\node_modules\contextify\build\contextify.vcxproj]
2015-12-02T09:09:22.4955630Z   
2015-12-02T09:09:22.4955630Z   
2015-12-02T09:09:22.5111722Z ##[error]gyp ERR! build error 
2015-12-02T09:09:22.5111722Z ##[error]gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
2015-12-02T09:09:22.5111722Z ##[error]gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
2015-12-02T09:09:22.5267977Z ##[error]gyp ERR! stack     at emitTwo (events.js:87:13)
2015-12-02T09:09:22.5267977Z ##[error]gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
2015-12-02T09:09:22.5267977Z ##[error]gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
2015-12-02T09:09:22.5267977Z ##[error]gyp ERR! System Windows_NT 6.3.9600
2015-12-02T09:09:22.5267977Z ##[error]gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
2015-12-02T09:09:22.5267977Z ##[error]gyp ERR! cwd D:\tfs-agent1\_work\f810d0d0\AceEditor\node_modules\node-jsdom\node_modules\contextify
2015-12-02T09:09:22.5267977Z ##[error]gyp ERR! node -v v4.2.2
2015-12-02T09:09:22.5267977Z ##[error]gyp ERR! node-gyp -v v3.0.3
2015-12-02T09:09:22.5267977Z ##[error]gyp ERR! not ok 
2015-12-02T09:09:22.6049164Z ##[error]npm ERR! Windows_NT 6.3.9600
2015-12-02T09:09:22.6049164Z ##[error]npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
2015-12-02T09:09:22.6049164Z ##[error]npm ERR! node v4.2.2
2015-12-02T09:09:22.6049164Z ##[error]npm ERR! npm  v2.14.7
2015-12-02T09:09:22.6049164Z ##[error]npm ERR! code ELIFECYCLE
2015-12-02T09:09:22.6049164Z ##[error]npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
2015-12-02T09:09:22.6049164Z ##[error]npm ERR! Exit status 1
2015-12-02T09:09:22.6049164Z ##[error]npm ERR! 
2015-12-02T09:09:22.6049164Z ##[error]npm ERR! Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.
2015-12-02T09:09:22.6049164Z ##[error]npm ERR! This is most likely a problem with the contextify package,
2015-12-02T09:09:22.6205479Z ##[error]npm ERR! not with npm itself.
2015-12-02T09:09:22.6205479Z ##[error]npm ERR! Tell the author that this fails on your system:
2015-12-02T09:09:22.6205479Z ##[error]npm ERR!     node-gyp rebuild
2015-12-02T09:09:22.6205479Z ##[error]npm ERR! You can get their info via:
2015-12-02T09:09:22.6205479Z ##[error]npm ERR!     npm owner ls contextify
2015-12-02T09:09:22.6205479Z ##[error]npm ERR! There is likely additional logging output above.
2015-12-02T09:09:23.1830543Z ##[error]npm ERR! Please include the following file with any support request:
2015-12-02T09:09:23.1830543Z ##[error]npm ERR!     D:\tfs-agent1\_work\f810d0d0\AceEditor\npm-debug.log
2015-12-02T09:09:23.2143015Z ##[error]Unexpected exit code 1 returned from tool npm.cmd
````

**Comment by nightwing** [comment]
It is needed for tests, use npm install --production to skip it

**Comment by westonized** [comment]
@nightwing Thanks, but now I can't build it, I guess because I need dry-ice and architect-build

````
2015-12-02T09:54:02.6973123Z ##[error]module.js:339
2015-12-02T09:54:02.6973123Z ##[error]    throw err;
2015-12-02T09:54:02.6973123Z ##[error]    ^
2015-12-02T09:54:02.6973123Z ##[error]Error: Cannot find module 'architect-build/copy'
2015-12-02T09:54:02.6973123Z ##[error]    at Function.Module._resolveFilename (module.js:337:15)
2015-12-02T09:54:02.6973123Z ##[error]    at Function.Module._load (module.js:287:25)
2015-12-02T09:54:02.6973123Z ##[error]    at Module.require (module.js:366:17)
2015-12-02T09:54:02.6973123Z ##[error]    at require (module.js:385:17)
2015-12-02T09:54:02.6973123Z ##[error]    at Object.<anonymous> (D:\tfs-agent1\_work\f810d0d0\AceEditor\Makefile.dryice.js:34:12)
2015-12-02T09:54:02.6973123Z ##[error]    at Module._compile (module.js:435:26)
2015-12-02T09:54:02.6973123Z ##[error]    at Object.Module._extensions..js (module.js:442:10)
2015-12-02T09:54:02.6973123Z ##[error]    at Module.load (module.js:356:32)
2015-12-02T09:54:02.6973123Z ##[error]    at Function.Module._load (module.js:311:12)
2015-12-02T09:54:02.6973123Z ##[error]    at Function.Module.runMain (module.js:467:10)
````

**Comment by nightwing** [comment]
Unfortunately npm still doesn't support Optional devDependencies https://github.com/npm/npm/issues/3870, i am not sure what to do here.
I usually set npm `rollback` to false as a workaround for cases like this.

**Comment by westonized** [comment]
@nightwing I'm new to npm and don't know what that would do for me. Unless it hides the error, I'll still get errors showing on my build server. For now I've deleted the dependency in my fork.

Any plans to update the dependency? node-jsdom is apparently abandon ware. One alternative could be https://github.com/cheeriojs/cheerio?

**Comment by nightwing** [comment]
now we use new version of node-jsdom, which does not require contextify
