### ISSUE TITLE
Unable to convert tmLanguage due error plist.parseString is not a function

### ISSUE THREAD

**Issue by igauravsehrawat** [ajaxorg/ace#3062]
Traceback is below
```
        plist.parseString(xmlOrJSON, function(_, result) {
              ^
TypeError: plist.parseString is not a function
    at exports.parsePlist (/Users/root3d/Projects/ace/tool/lib.js:12:15)
    at convertTmLanguage (/Users/root3d/Projects/ace/tool/tmlanguage.js:632:5)
    at fetchAndConvert (/Users/root3d/Projects/ace/tool/tmlanguage.js:627:5)
    at Array.forEach (native)
    at Object.<anonymous> (/Users/root3d/Projects/ace/tool/tmlanguage.js:694:10)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
```

System configuration:
```
Node: v5.10.1
NPM: 3.8.6
OS: Mac OSX
```

Can anyone guide me in right direction?

Thanks.

**Comment by Noctisdark** [comment]
You must you `plist.parse`, and note however, that `plist.parse` is not asynchronous.
So instead of using `plist.parse(xml, callback)`, you should use `callback(plist.parse(xml))`. I think ACE is still using the older version of `plist`.

**Comment by igauravsehrawat** [comment]
@Noctisdark Thanks. You were right, Ace is using older version of plist, all `callback` usage was helpful.
But seems like a lot is broken, I hit the bump again.
```
Updated modelist at: /Users/root3d/Projects/my-language/ace/lib/ace/ext/modelist.js

created file /Users/root3d/Projects/my-language/ace/lib/ace/mode/clay_highlight_rules.js
testing highlighter
[TypeError: Cannot read property 'onMatch' of undefined]
/Users/root3d/Projects/my-language/ace/tool/tmlanguage.js:633
        var highlighterFilename = lib.snakeCase(language.name).replace(/[^\w]/g, "");
                                                        ^

TypeError: Cannot read property 'name' of undefined
    at /Users/root3d/Projects/my-language/ace/tool/tmlanguage.js:633:57
    at exports.parsePlist (/Users/root3d/Projects/my-language/ace/tool/lib.js:31:17)
    at convertTmLanguage (/Users/root3d/Projects/my-language/ace/tool/tmlanguage.js:632:5)
    at fetchAndConvert (/Users/root3d/Projects/my-language/ace/tool/tmlanguage.js:627:5)
    at Array.forEach (native)
    at Object.<anonymous> (/Users/root3d/Projects/my-language/ace/tool/tmlanguage.js:694:10)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

Is it due to outdated code or else?

Thanks

**Comment by igauravsehrawat** [comment]
@Noctisdark More progress made
I noticed `plist.parse` wanted XMLorJSON in it's argument, so I provided JSON myself converted from tmLanguage.
Got new error.
```
Updated modelist at: /Users/root3d/Projects/ace/lib/ace/ext/modelist.js

created file /Users/root3d/Projects/ace/lib/ace/mode/my-language_highlight_rules.js
testing highlighter
[TypeError: Cannot read property 'onMatch' of undefined]
```

**Comment by Noctisdark** [comment]
I got this error, I just remove the `test` function, and I really don't know much about that. Just loaded the language using `session.setMode` and it worked.

**Comment by igauravsehrawat** [comment]
@Noctisdark Thanks for the help.
I set the mode but it's not working. I am still getting `ace.js:5191 Uncaught TypeError: Cannot read property 'onMatch' of undefined` in dev tools.

So I figured out that it's looking for rules but it's seems like the converter isn't producing highlighting rules somehow. 😞 
```
var MyLangHighlightRules = function() {

    this.$rules = {
        start: []
    }
    
    this.normalizeRules();
};
```
Converter just produced meta-data.
It seems like I have to write the highlighting rules myself.

Cheers

**Comment by nightwing** [comment]
@igauravsehrawat https://github.com/ajaxorg/ace/commit/abab9a3135b7cd68e7cb5637ce57ac54e37242ab fixes the issue with wrong version of plist.
Could you try it again now? If it doesn't work please show the tmlanguage file, and i'll try to debug why it doesn't work

**Comment by igauravsehrawat** [comment]
@nightwing Thanks. Now, I am not getting any error about `plist.parseString is not a function`.
But I am still stuck with error `testing highlighter
[TypeError: Cannot read property 'onMatch' of undefined]` . Same error appears on dev tools while testing the language.

Here is my sample tmLanguage file
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>contexts</key>
    <dict>
        <key>c_interface_keywords</key>
        <array>
            <dict>
                <key>match</key>
                <string>(@[A-Za-z_]*[A-Za-z0-9_]*)</string>
                <key>scope</key>
                <string>keyword.other.my_lang</string>
            </dict>
        </array>
        <key>comments</key>
        <array>
            <dict>
                <key>match</key>
                <string>//.*?\n</string>
                <key>scope</key>
                <string>comment.line.double-slash.my_lang</string>
            </dict>
            <dict>
                <key>match</key>
                <string>/\*</string>
                <key>push</key>
                <array>
                    <dict>
                        <key>meta_scope</key>
                        <string>comment.block.my_lang</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\*/\n?</string>
                        <key>pop</key>
                        <true/>
                        <key>scope</key>
                        <string>punctuation.definition.comment.my_lang</string>
                    </dict>
                </array>
                <key>scope</key>
                <string>punctuation.definition.comment.my_lang</string>
            </dict>
        </array>
        <key>conditionals</key>
        <array>
            <dict>
                <key>match</key>
                <string>\b(if|else|for|in|while|break|continue|return|assert)(?!\?)\b</string>
                <key>scope</key>
                <string>keyword.conditionals.my_lang</string>
            </dict>
        </array>
        <key>constants</key>
        <array>
            <dict>
                <key>match</key>
                <string>\b(true|false)(?!\?)\b</string>
                <key>scope</key>
                <string>constant.language.my_lang</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(void|new)(?!\?)\b</string>
                <key>scope</key>
                <string>constant.language.my_lang</string>
            </dict>
        </array>
        <key>main</key>
        <array>
            <dict>
                <key>include</key>
                <string>comments</string>
            </dict>
            <dict>
                <key>include</key>
                <string>numbers</string>
            </dict>
            <dict>
                <key>include</key>
                <string>c_interface_keywords</string>
            </dict>
            <dict>
                <key>include</key>
                <string>constants</string>
            </dict>
            <dict>
                <key>include</key>
                <string>operators</string>
            </dict>
            <dict>
                <key>include</key>
                <string>conditionals</string>
            </dict>
        </array>
    <key>file_extensions</key>
    <array>
        <string>my_lang</string>
    </array>
    <key>name</key>
    <string>My_lang</string>
    <key>scope</key>
    <string>source.my_lang</string>
</dict>
</plist>
```

I had `sublime-syntax`[1] file for the language, then I used SublimeText's `PackageDev`[2] repo to convert it to tmLanguage. 

[1]: https://www.sublimetext.com/docs/3/syntax.html
[2]: https://github.com/SublimeText/PackageDev#syntax-definition-development

Thanks

**Comment by nightwing** [comment]
Looks like PackageDev doesn't actually convert to textmate format, it just changes yaml to plist.
Could you show the sublime-syntax file? looks like converting it directly will be easier because the format is very close to what is used by ace

**Comment by igauravsehrawat** [comment]
@nightwing Ok.

Here is sublime syntax file [[1]]

[1]: https://gist.github.com/igauravsehrawat/f2dc7e7c9c5b5b8d215552dbf1df8663

Thanks

**Comment by igauravsehrawat** [comment]
I have converted my sublime-syntax to Ace highlighter. Also syntax error issue was solved, hence closing the issue.

Thanks @nightwing @Noctisdark
