### ISSUE TITLE
Crash to intall =/

### ISSUE THREAD

**Issue by marcobraghim** [ajaxorg/ace#3613]
```
$ node Makefile.dryice.js full -m --target ./build
# ace License | Readme | Changelog ---------
# ace ---------
fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir './build/src-noconflict'
    at Object.fs.readdirSync (fs.js:904:18)
    at buildTypes (/var/www/marcomoveleiro/fun-editor/ace/Makefile.dryice.js:118:10)
    at ace (/var/www/marcomoveleiro/fun-editor/ace/Makefile.dryice.js:111:5)
    at main (/var/www/marcomoveleiro/fun-editor/ace/Makefile.dryice.js:71:13)
    at Object.<anonymous> (/var/www/marcomoveleiro/fun-editor/ace/Makefile.dryice.js:661:5)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

```

**Comment by nightwing** [comment]
Should be fixed now, thanks for the report!
