### ISSUE TITLE
Running build always results in an error in the mkdirp dependency

### ISSUE THREAD

**Issue by VAlex0** [ajaxorg/ace#4165]
First i thought i was doing something wrong, but it looks like a dependency is not compatible anymore.

I tried to build on Windows and Debian, like it's written in the README and like i did it several times over the last months. But now i always get this error (even with old versions of ace).

```console
$ node ./Makefile.dryice.js
Processing 71 files.
Compressing:  false
C:\Users\me\Documents\ace\node_modules\mkdirp\lib\op
ts-arg.js:13
    throw new TypeError('invalid options argument')
    ^

TypeError: invalid options argument
    at optsArg (C:\Users\me\Documents\ace\node_modul
es\mkdirp\lib\opts-arg.js:13:11)
    at mkdirp (C:\Users\me\Documents\ace\node_module
s\mkdirp\index.js:11:10)
    at createOutputFolder (C:\Users\me\Documents\ace
\node_modules\architect-build\build.js:158:5)
    at Function.writeToFile (C:\Users\me\Documents\a
ce\node_modules\architect-build\build.js:391:5)
    at write (C:\Users\me\Documents\ace\Makefile.dry
ice.js:323:15)
    at Stream.<anonymous> (C:\Users\me\Documents\ace
\node_modules\architect-build\build.js:147:13)
    at Stream.emit (events.js:164:20)
    at C:\Users\me\Documents\ace\node_modules\archit
ect-build\module-deps.js:212:20
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

```

**Comment by nightwing** [comment]
This should be fixed with https://github.com/ajaxorg/ace/commit/dbac92c7cfe694dbb15c74437714908fcae178f0. Thanks for reporting!
