### ISSUE TITLE
Maximum call stack size exceeded when building with Makefile.dryice.js

### ISSUE THREAD

**Issue by xu-xionglong** [ajaxorg/ace#4596]
xxl@xxldeMacBook-Air ace % node Makefile.dryice.js full --target ../ace-builds
# ace License | Readme | Changelog ---------
# ace ---------
# kitchen sink ---------
"../build/
"../build/
"../build/
"../build/
"../build/
"../build/
"../build/
Processing 70 files.
Compressing:  false
/Users/xxl/Documents/projects/ace/Makefile.dryice.js:569
    result.sources.forEach(function(pkg) {
                                   ^

RangeError: Maximum call stack size exceeded
    at /Users/xxl/Documents/projects/ace/Makefile.dryice.js:569:36
    at Array.forEach (<anonymous>)
    at getLoadedFileList (/Users/xxl/Documents/projects/ace/Makefile.dryice.js:569:20)
    at /Users/xxl/Documents/projects/ace/Makefile.dryice.js:565:13
    at /Users/xxl/Documents/projects/ace/Makefile.dryice.js:259:21
    at write (/Users/xxl/Documents/projects/ace/Makefile.dryice.js:296:20)
    at buildAceModuleInternal (/Users/xxl/Documents/projects/ace/Makefile.dryice.js:275:16)
    at Function.buildAceModule.dequeue (/Users/xxl/Documents/projects/ace/Makefile.dryice.js:254:40)
    at /Users/xxl/Documents/projects/ace/Makefile.dryice.js:261:24
    at write (/Users/xxl/Documents/projects/ace/Makefile.dryice.js:296:20)

**Comment by kevinushey** [comment]
I bumped into this as well. My guess is that newer versions of Node / V8 have changed (decreased?) the default stack size.

The following should suffice as a workaround:

```
node --stack_size=2048 Makefile.dryice.js
```

**Comment by andrewnester** [comment]
Providing `--stack_size` option solves the problem, closing the issue
