### ISSUE TITLE
Emmet-Core doesn't work with Ace

### ISSUE THREAD

**Issue by L1ghtingBolt** [ajaxorg/ace#4613]
I am trying to add Emmet to my Ace app. It gave me a warning:
`script for emmet-core is not loaded`

I installed emmet-core, imported it and... Worked! I was happy, did more modifications... But when I built the package, It gave me an error:
`Octal literal is not allowed in strict mode`

What can I do to use emmet?

Using common emmet doesn't work and gives this warning:
ace.js:3621 TypeError: emmet.require is not a function
    at AceEmmetEditor.setupContext (ext-emmet.js:1025:50)
    at Object.runEmmetCommand [as exec] (ext-emmet.js:1219:21)
    at ace.js:11528:26
    at CommandManager.EventEmitter._emit.EventEmitter._dispatchEvent (ace.js:3468:16)
    at CommandManager.exec (ace.js:11559:30)
    at KeyBinding.$callKeyboardHandlers (ace.js:4229:36)
    at KeyBinding.onCommandKey (ace.js:4253:21)
    at Editor.onCommandKey (ace.js:13414:32)
    at normalizeCommandKeys (ace.js:894:12)
    at HTMLText

**Comment by andrewnester** [comment]
Please see our demo for emmet app
https://ace.c9.io/demo/emmet.html
