### ISSUE TITLE
Error parsing regex in lucene mode

### ISSUE THREAD

**Issue by dennisoelkers** [ajaxorg/ace#5135]
### Describe the bug

When using a regex to match a field's value in lucene mode, an exception is being thrown.

### Expected Behavior

The snippet should parse properly.

### Current Behavior

An exception is thrown:

```
caught Error: state doesn't exist
    at Tokenizer.reportError (ace.js:996:13)
    at Tokenizer.getLineTokens (ace.js:5491:30)
    at BackgroundTokenizer.$tokenizeRow (ace.js:7177:35)
    at BackgroundTokenizer.getTokens (ace.js:7167:40)
    at EditSession.getTokens (ace.js:8970:33)
    at Text.$renderLine (ace.js:15856:39)
    at Text.$renderLinesFragment (ace.js:15555:18)
    at Text.update (ace.js:15575:25)
    at VirtualRenderer.$renderChanges (ace.js:17489:29)
    at RenderLoop._flush (ace.js:16563:23)
```

### Reproduction Steps

1. Use [ace kitchen sink](https://ace.c9.io/build/kitchen-sink.html). 
2. Switch mode to lucene. 
3. Open browser's JS console. 
4. Enter this snippet: `foo:/bar/`.
5. See exception in console.

### Ace Version / Browser / OS / Keyboard layout

1.17.0

**Comment by akoreman** [comment]
A fix for this was released as part of version 1.18.1.
