### ISSUE TITLE
tool/tmTheme.js doesn't immediately work due to deprecation

### ISSUE THREAD

**Issue by NotLazy** [ajaxorg/ace#5237]
### Describe the bug

When cloning this repo and attempting to use the tmTheme converter tool, I get a `parseString is not a function` error

### Expected Behavior

I expect there to not be an error and for the tmTheme to be converted

### Current Behavior

I get the below error
```
Converting myTheme
/Users/lunaalfien/dev/ace/tool/tmtheme.js:9
    parseString(themeXml, function(_, theme) {
    ^

TypeError: parseString is not a function
    at parseTheme (/Users/lunaalfien/dev/ace/tool/tmtheme.js:9:5)
    at convertTheme (/Users/lunaalfien/dev/ace/tool/tmtheme.js:313:5)
    at Object.<anonymous> (/Users/lunaalfien/dev/ace/tool/tmtheme.js:385:5)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.12.1
```

### Reproduction Steps

```sh
git clone https://github.com/ajaxorg/ace.git
cp theme.tmTheme ace/
cd ace/tool
npm i
cd ..
node myTheme tool/tmTheme.js theme.tmTheme ./
```

### Possible Solution

Update the tool to use the latest version of plist.js

### Additional Information/Context

It seems that parseString has been deprecated in plist.js since v1.2.0 but the version that gets installed when using `npm i` is v3.0.5

Source: https://github.com/TooTallNate/plist.js/commit/e0877a108f4b464f2f089599d30c6b90054e952d

### Ace Version / Browser / OS / Keyboard layout

v1.23.1 / NodeJS v18.12.1 / MacOS 10.15 / QWERTY

**Comment by akoreman** [comment]
Thanks for opening this issue, the method we use does indeed seem to be removed from the dependency. The method used in the linked PR does seem like the method we should use now (defined [here](https://github.com/TooTallNate/plist.js/blob/master/lib/parse.js#L75)).
